config/routes.rb
# frozen_string_literal: true

require 'karafka/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
  root 'main#show'

  resources :visitors, only: %i[index show]

  mount Karafka::Web::App, at: '/karafka'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/visit.rb
class Visit < ApplicationRecord
  scope :recent, -> { joins(:visitor).order(visited_at: :desc).limit(10) }

  belongs_to :visitor
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  has_many :visits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :assign_visitor_id
  before_action :track_visit

  private

  def assign_visitor_id
    session[:visitor_id] ||= SecureRandom.uuid
  end

  def track_visit
    VisitorsJob.perform_later(session[:visitor_id])

    Karafka.producer.produce_async(
      topic: 'visits',
      payload: {
        id: SecureRandom.uuid,
        visited_at: Time.zone.now,
        visitor_id: session[:visitor_id],
        page_path: request.path
      }.to_json
    )
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def show
    @recent_visits = Visit.recent
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @visitors = Visitor.order(created_at: :desc).limit(10)
  end

  def show
    @visitor = Visitor.find(params[:id])
    @visits = @visitor.visits.order(visited_at: :desc).first(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Visitors App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Visitors App</a>

        <div class="collapse navbar-collapse container" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= visitors_path %>">Visitors</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <main class="container">
      <div class="bg-light p-5">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/main/show.html.erb
<h3>Recent visits</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Request id</th>
      <th>Visitor id</th>
      <th>Visited at</th>
      <th>Page path</th>
    </tr>
  </thead>
  <tbody>
    <% @recent_visits.each do |visit| %>
      <tr>
        <td><%= visit.id %></td>
        <td><%= link_to visit.visitor.id, visitor_path(visit.visitor) %></td>
        <td><%= visit.visited_at %></td>
        <td><%= visit.page_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/visitors/index.html.erb
<h3>Newly created visitors</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Created at</th>
    </tr>
  </thead>
  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= link_to visitor.id, visitor %></td>
        <td><%= visitor.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/visitors/show.html.erb
<h3>Visitor recent visits</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Request id</th>
      <th>Visited at</th>
      <th>Page path</th>
    </tr>
  </thead>
  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.id %></td>
        <td><%= visit.visited_at %></td>
        <td><%= visit.page_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>